//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtBazaar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnički_podaci
    {
        public int Id_kupnje { get; set; }
        public int Broj_kartice { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Adresa { get; set; }
    }
}
